name: Build and push image Java Spring Boot
on:
  workflow_dispatch: {}

jobs:

    extract-version:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Get Version from changelog
          id: extract_version
          run: |
            VERSION=$(grep -oPm1 "(?<=## \[)[^]]+" CHANGELOG.md)
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    build:
        name: Build and push Docker image
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Build dockerfile
          env:
            IMAGE_TAG: ${{ steps.extract_version.outputs.VERSION }}
          run: docker build -t mi-app:$IMAGE_TAG .
        
        - name: Validate docker image
          env:
            IMAGE_TAG: ${{ steps.extract_version.outputs.VERSION }}        
          run: |
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            echo -e "\e[32mdocker ps -a!\e[0m"
            docker ps -a
            echo -e "\e[32mdocker images!\e[0m"
            docker images
            echo -e "\e[32mdocker run!\e[0m"
            docker run -d --name mi-app-container -p 8081:8081 -e SERVERS_ADRESS=0.0.0.0 mi-app:$IMAGE_TAG
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            sleep 20      
            echo -e "\e[32mdocker logs mi-app-container!\e[0m"
            docker logs mi-app-container
            echo -e "\e[32mValidar curl!\e[0m"
            curl -f http://localhost:8081/weatherForecast || (echo "Curl failed" && exit 1)
            echo -e "\e[32mdocker stop mi-app-container!\e[0m"
            docker stop mi-app-container
            docker logs mi-app-container
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            echo -e "\e[32mdocker ps -a!\e[0m"
            docker ps -a
            echo -e "\e[32mdocker rm mi-app-container (eliminar)!\e[0m"
            docker rm mi-app-container
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            echo -e "\e[32mdocker ps -a!\e[0m"
            docker ps -a     
            echo -e "\e[32mdocker rmi mi-app:1.0.0 (eliminar)!\e[0m"
            docker rmi mi-app:$IMAGE_TAG
            echo -e "\e[32mdocker ps!\e[0m"
            docker images

