name: Build and push image Dotnet
on:
  workflow_dispatch: {}

jobs:

    extract-version:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Get Version from changelog
          id: extract_version
          run: |
            VERSION=$(grep -oPm1 "(?<=## \[)[^]]+" CHANGELOG.md)
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    build:
        name: Build and push Docker image
        needs: extract-version
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Build dockerfile
          run: docker build -t mi-app:1.0.0 .
        
        - name: Validate docker image
          run: |
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            echo -e "\e[32mdocker ps -a!\e[0m"
            docker ps -a
            echo -e "\e[32mdocker images!\e[0m"
            docker images
            echo -e "\e[32mdocker run!\e[0m"
            docker run -d --name mi-app-container -p 8080:8080 -e SERVERS_ADRESS=0.0.0.0 mi-app:1.0.0
            echo -e "\e[32mdocker ps!\e[0m"
            docker ps
            sleep 20      
            echo -e "\e[32mdocker logs mi-app-container!\e[0m"
            docker logs mi-app-container
            echo -e "\e[32mValidar curl!\e[0m"
            curl -f http://localhost:8080 || (echo "Curl failed" && exit 1)


